system:
    api:
        host: "127.0.0.1"
        port: 8000
    ui:
        host: "127.0.0.1"
        port: 8501

paths:
    data_dir: "data"
    models_dir: "models"
    logs_dir: "logs"
    trends_file: "component_trends.csv"
    metadata_file: "components_metadata.csv"

data:
    test_size: 0.2
    val_size: 0.3
    shuffle: true